version: '2'

services:

  jenkins:
    image: nathema/jenkins-sfdx
    restart: unless-stopped
    volumes:
      - './jenkins_home:/var/jenkins_home'
    ports:
      - "8080"

  nginx:
    image: nginx
    restart: unless-stopped
    links:
      - jenkins
    volumes:
      - "./etc/nginx/conf.d/:/etc/nginx/conf.d/"
    environment:
      VIRTUAL_HOST: ci.sfdev.eu
      LETSENCRYPT_HOST: ci.sfdev.eu
      LETSENCRYPT_EMAIL: peter@sfdev.eu

  nginx-proxy:
    image: jwilder/nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./nginx/vhost.d:/etc/nginx/vhost.d"
      - "./nginx/html:/usr/share/nginx/html"
      - "./nginx/certs:/etc/nginx/certs"
      - "/var/run/docker.sock:/tmp/docker.sock:ro"

  letsencrypt-nginx-proxy-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: unless-stopped
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    volumes_from:
      - "nginx-proxy"

